# Generated by Django 5.0 on 2023-12-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
