# Generated by Django 5.0 on 2023-12-15 21:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postattachment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
